// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksqancbnwkzvsskfrsul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzcWFuY2Jud2t6dnNza2Zyc3VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxNzg0NjEsImV4cCI6MjA3OTc1NDQ2MX0.0e42tHClUsaSA9cWxYdfZhzcVD8-rAvbjqDGvPpYEMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);